spring.application.name=pos-studio-papel-api

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/pos_papel
spring.datasource.username=postgres
spring.datasource.password=sohaz322
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# FLYWAY
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# ===============================
# SERVER
# ===============================
server.port=8080
jwt.secret= qk6C6J3Ws8b1x0F3Hr9n3woiPX+0SHr7m1nh0h2rw5o=